// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TvoeTiloApp.Infrastructure.DataAccess.DbContexts;

#nullable disable

namespace TvoeTiloApp.Infrastructure.DataAccess.Migrations
{
    [DbContext(typeof(TvoeTiloAppDbContext))]
    [Migration("20260507170318_AddedBasicStructure")]
    partial class AddedBasicStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClientProfileScheduledTraining", b =>
                {
                    b.Property<int>("ClientProfilesClientProfileId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduledTrainingsScheduledTrainingId")
                        .HasColumnType("int");

                    b.HasKey("ClientProfilesClientProfileId", "ScheduledTrainingsScheduledTrainingId");

                    b.HasIndex("ScheduledTrainingsScheduledTrainingId");

                    b.ToTable("ClientProfileScheduledTraining");
                });

            modelBuilder.Entity("CoachProfileTrainingType", b =>
                {
                    b.Property<int>("CoachProfilesCoachProfileId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingTypesTrainingTypeId")
                        .HasColumnType("int");

                    b.HasKey("CoachProfilesCoachProfileId", "TrainingTypesTrainingTypeId");

                    b.HasIndex("TrainingTypesTrainingTypeId");

                    b.ToTable("CoachProfileTrainingType");
                });

            modelBuilder.Entity("TvoeTiloApp.Domain.Entities.ClientProfile", b =>
                {
                    b.Property<int>("ClientProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientProfileId"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ClientProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ClientProfile");
                });

            modelBuilder.Entity("TvoeTiloApp.Domain.Entities.CoachProfile", b =>
                {
                    b.Property<int>("CoachProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoachProfileId"));

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CoachProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CoachProfile");
                });

            modelBuilder.Entity("TvoeTiloApp.Domain.Entities.ScheduledTraining", b =>
                {
                    b.Property<int>("ScheduledTrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduledTrainingId"));

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainingTypeId")
                        .HasColumnType("int");

                    b.HasKey("ScheduledTrainingId");

                    b.HasIndex("TrainingTypeId");

                    b.ToTable("ScheduledTraining");
                });

            modelBuilder.Entity("TvoeTiloApp.Domain.Entities.TrainingType", b =>
                {
                    b.Property<int>("TrainingTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainingTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrainingTypeId");

                    b.ToTable("TrainingType");
                });

            modelBuilder.Entity("TvoeTiloApp.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ClientProfileScheduledTraining", b =>
                {
                    b.HasOne("TvoeTiloApp.Domain.Entities.ClientProfile", null)
                        .WithMany()
                        .HasForeignKey("ClientProfilesClientProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TvoeTiloApp.Domain.Entities.ScheduledTraining", null)
                        .WithMany()
                        .HasForeignKey("ScheduledTrainingsScheduledTrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoachProfileTrainingType", b =>
                {
                    b.HasOne("TvoeTiloApp.Domain.Entities.CoachProfile", null)
                        .WithMany()
                        .HasForeignKey("CoachProfilesCoachProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TvoeTiloApp.Domain.Entities.TrainingType", null)
                        .WithMany()
                        .HasForeignKey("TrainingTypesTrainingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TvoeTiloApp.Domain.Entities.ClientProfile", b =>
                {
                    b.HasOne("TvoeTiloApp.Domain.Entities.User", "User")
                        .WithOne("ClientProfile")
                        .HasForeignKey("TvoeTiloApp.Domain.Entities.ClientProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TvoeTiloApp.Domain.Entities.CoachProfile", b =>
                {
                    b.HasOne("TvoeTiloApp.Domain.Entities.User", "User")
                        .WithOne("CoachProfile")
                        .HasForeignKey("TvoeTiloApp.Domain.Entities.CoachProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TvoeTiloApp.Domain.Entities.ScheduledTraining", b =>
                {
                    b.HasOne("TvoeTiloApp.Domain.Entities.TrainingType", "TrainingType")
                        .WithMany("ScheduledTrainings")
                        .HasForeignKey("TrainingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingType");
                });

            modelBuilder.Entity("TvoeTiloApp.Domain.Entities.TrainingType", b =>
                {
                    b.Navigation("ScheduledTrainings");
                });

            modelBuilder.Entity("TvoeTiloApp.Domain.Entities.User", b =>
                {
                    b.Navigation("ClientProfile");

                    b.Navigation("CoachProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
