<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TvoeTiloApp.Domain\TvoeTiloApp.Domain.csproj" />
    <ProjectReference Include="..\TvoeTiloApp.Model\TvoeTiloApp.Model.csproj" />
  </ItemGroup>

</Project>
